# Generated by Django 4.1.1 on 2022-10-05 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=500)),
                ('auxiliar', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(max_length=50, verbose_name='Nombre del paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oximetria', models.FloatField(max_length=5, verbose_name='Oximetria')),
                ('f_respiratoria', models.FloatField(max_length=5, verbose_name='Frecuencia respiratoria')),
                ('f_cardiaca', models.FloatField(max_length=5, verbose_name='Frecuencia cardiaca')),
                ('temperatura', models.FloatField(max_length=5, verbose_name='Temperatura')),
                ('p_arterial', models.FloatField(max_length=5, verbose_name='Presion arterial')),
                ('glicemias', models.FloatField(max_length=5, verbose_name='Glicemias')),
                ('diagnostico', models.CharField(max_length=500, verbose_name='Diagnostico')),
                ('cuidados', models.CharField(max_length=500, verbose_name='Cuidados')),
                ('fecha_reporte', models.DateTimeField()),
                ('fecha_analisis_medico', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=50, verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('rol', models.CharField(choices=[('A', 'Auxiliar'), ('E', 'Enfermero'), ('M', 'Medico'), ('P', 'Paciente'), ('F', 'Familiar Paciente')], default='P', max_length=50, verbose_name='Rol')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('tipoDocumento', models.CharField(choices=[('RC', 'Registro Civil'), ('TI', 'Tarjeta de Identidad'), ('CC', 'Cedula de Ciudadania')], default='CC', max_length=50, verbose_name='Tipo de documento')),
                ('documento', models.PositiveIntegerField(default=0, verbose_name='Documento')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('celular', models.CharField(max_length=10, verbose_name='Celular')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=50, verbose_name='Genero')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enfermero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.enfermero')),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.familiar')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.historia')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.medico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familiar',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enfermero',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
