# Generated by Django 4.1.1 on 2022-10-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='nombre_paciente',
            field=models.CharField(max_length=50),
        ),
    ]
